[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scorpy"
version = "0.1.0"
description = "Scattering Correlation for Python"
requires-python = ">=3.13.11" 
dependencies = [
    "numpy==2.3.5",
    "matplotlib==3.10.8",
    "h5py==3.15.1",
    "pyshtools==4.13.1",
    "pycifrw==5.0.1"
]

[project.optional-dependencies]
docs = [
    "sphinx>=7.0.0",
    "pydata-sphinx-theme>=0.15.0",
]
